"use client";
import "./globals.css";
import { Inter } from "next/font/google";
import { Providers } from "./redux/provider";
import { Auth0Provider } from "@auth0/auth0-react";
import * as React from "react";
import MainLayout from "./MainLayout";
import { ThemeProvider } from "next-themes";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={[
          inter.className,
          "overflow-y-scroll overflow-x-hidden scrollbar-thin scrollbar-thumb-blue-950 ",
        ]}
      >
        <Auth0Provider
          // domain="dev-iowgyvpozp2mgygz.au.auth0.com"
          // clientId="XH0J8tcjNh3oGIVEf4odrZWYffJkxOhR"
          domain="dev-xy0ifih1jvc3gskx.us.auth0.com"
          clientId="zRq1LEPYH832oGzA1RpR3gMK4EhDHm0N"
          authorizationParams={{
            redirect_uri: "http://localhost:3000",
          }}
        >
          <ThemeProvider
            attribute="class"
            enableSystem={false}
            defaultTheme="dark"
          >
            <Providers>
              <MainLayout>{children}</MainLayout>
            </Providers>
          </ThemeProvider>
        </Auth0Provider>
      </body>
    </html>
  );
}
